import MorningBrief from './260925';

const source = 'Bigdata.com (calendário econômico e corporativo, 25/09); Benzinga (pré-market de 25/09); Investing.com (mercados de 25/09).';
const drivers = [
  ['Futuros avançam', 'Dow +0,36% · S&P 500 +0,37% · Nasdaq 100 +0,66% no levantamento pré-market da Benzinga.', 'O Nasdaq liderava os ganhos; observar a sustentação na abertura.'],
  ['Petróleo e geopolítica', 'WTI perto de US$ 92,81 (-1,9%) e DXY em 101,03 (-0,25%) na sessão americana inicial, segundo Benzinga. A imprensa relata proposta iraniana condicionada para reabrir Hormuz.', 'O alívio no petróleo pode reduzir a pressão sobre expectativas de inflação; a proposta ainda depende de condições.'],
  ['Dados mistos e juros altos', 'Bens duráveis 0,0% ante -0,4% esperado; ex-transportes +0,3% ante +0,6%; core capex +1,6% ante +0,5%. Treasury 10Y perto de 5,175% no levantamento Benzinga.', 'Investimento empresarial surpreendeu positivamente, mas o custo de capital continua elevado.'],
];
const Box = ({title, children}:{title:string;children:React.ReactNode}) => <section className='rounded-2xl border border-slate-800 bg-slate-900/80 p-5'><h2 className='mb-3 text-sm font-bold uppercase tracking-widest text-cyan-400'>{title}</h2><div className='space-y-3 text-sm leading-7 text-slate-200'>{children}</div></section>;
export default function FinalPremarket() {
 return <main className='min-h-screen bg-slate-950 text-slate-100'><div className='mx-auto max-w-6xl space-y-5 px-4 py-8'>
 <header className='border-b border-slate-800 pb-6'><p className='text-cyan-400'>PRIMESPHERE INTELLIGENCE · 25/09/2026</p><h1 className='mt-2 text-3xl font-bold md:text-5xl'>FINAL PRÉ-MARKET</h1><p className='mt-3 text-cyan-200'>Atualização editorial: 15:15 Madrid (CEST) · 09:15 Nova York (EDT)</p><p className='mt-2 text-xl font-semibold'>WALL STREET ABRE EM 15 MINUTOS</p><p className='mt-3 text-xs text-slate-400'>Horário de referência desta atualização: 15:15 Europe/Madrid. Cotações são snapshots pré-market, não preços em tempo real.</p></header>
 <Box title='Wall Street em 30 segundos'><div className='grid grid-cols-2 gap-3 md:grid-cols-3'>{[['Dow futuro','+0,36%'],['S&P 500 futuro','+0,37%'],['Nasdaq 100 futuro','+0,66%'],['Treasury 10Y','5,175%'],['WTI','US$ 92,81 · -1,9%'],['DXY','101,03 · -0,25%']].map(([n,v])=><div key={n} className='rounded-xl bg-slate-950 p-3'><p className='text-xs text-slate-400'>{n}</p><p className='mt-2 text-xl font-semibold'>{v}</p></div>)}</div><p className='text-xs text-slate-400'>Fonte: Benzinga, pré-market de 25/09; horários de cada instrumento podem diferir.</p></Box>
 <Box title='Mudou desde o Morning Brief'><p>Os bens duráveis de agosto já foram divulgados às 14:30 Madrid. O total veio acima do consenso, mas o indicador sem transportes ficou abaixo; core capex surpreendeu positivamente. O noticiário também passou a destacar a proposta iraniana condicionada de reabertura do Estreito de Hormuz. Comparações numéricas entre snapshots exigem cautela porque os horários das fontes diferem.</p></Box>
 <div className='grid gap-4 md:grid-cols-3'>{drivers.map(([t,n,i])=><Box key={t} title={t}><p><strong>NÚMERO / FATO:</strong> {n}</p><p><strong>IMPACTO / LEITURA:</strong> {i}</p></Box>)}</div>
 <div className='grid gap-4 md:grid-cols-2'><Box title='Dados econômicos já divulgados'><p>Bens duráveis: <strong>0,0%</strong> vs. -0,4% esperado; anterior revisado para +0,9%. Ex-transportes: <strong>+0,3%</strong> vs. +0,6%; anterior revisado para +0,7%. Bens de capital sem defesa e aeronaves: <strong>+1,6%</strong> vs. +0,5%; anterior revisado para +0,6%. Fonte: calendário Bigdata.com.</p></Box>
 <Box title='Premarket Movers'><p><strong>AKAM:</strong> +21,3% no snapshot validado do pré-market, após notícia de acordo de nuvem de US$ 11,6 bilhões com a Anthropic. Variação indicativa de um corte anterior, não cotação em tempo real. Outros movimentos sem confirmação recente não são reproduzidos.</p></Box>
 <Box title='Treasury · petróleo · dólar · VIX'><p>10Y: 5,175%; WTI: US$ 92,81 (-1,9%); DXY: 101,03 (-0,25%). Brent e VIX: sem nova cotação confirmada para este corte; não reutilizamos valores antigos como atuais.</p></Box>
 <Box title='Earnings Radar e agenda remanescente'><p>Ferrellgas Partners (FGPR): teleconferência Q4 às 15:00 Madrid, segundo Bigdata.com; resultado efetivo não confirmado neste corte. Michigan às <strong>16:00 Madrid</strong>: sentimento final, consenso 47,6; inflação esperada em 1 ano, consenso 4,6%; em 5 anos, 3,4%. Beth Hammack (Fed) às <strong>20:00 Madrid</strong>.</p></Box></div>
 <Box title='O que observar na abertura'><p>Às 15:30 Madrid: verificar se a liderança do Nasdaq se sustenta; acompanhar a reação dos yields e do petróleo às notícias sobre Hormuz; monitorar AKAM e, às 16:00, comparar Michigan e expectativas de inflação com o consenso.</p></Box>
 <Box title='Timeline editorial'><p><strong>12:34 Madrid:</strong> Morning Brief publicado e preservado abaixo.</p><p><strong>15:15 Madrid:</strong> Final Pré-Market — atualização da mesma edição, com dados divulgados e nova leitura da abertura.</p></Box>
 <Box title='Fontes e método'><p>{source}</p><p><a className='text-cyan-300 underline' href='https://www.benzinga.com/markets/equities/26/09/61990972/stock-market-today-dow-sp-500-nasdaq-futures-rise-amid-optimism-following-irans-offer-to-reopen-strait-of-hormuz-akam-cost-schl-in-focus'>Benzinga: pré-market 25/09</a> · <a className='text-cyan-300 underline' href='https://ng.investing.com/news/stock-market-news/us-stock-futures-drift-lower-as-soaring-yields-oil-prices-weigh-2708977'>Investing.com: futuros e petróleo</a>. Interpretações editoriais não são causalidades demonstradas. Conteúdo informativo, não recomendação de investimento.</p></Box>
 <details className='rounded-xl border border-slate-700' id='morning-brief'><summary className='cursor-pointer p-5 text-lg font-semibold text-cyan-300'>Consultar Morning Brief original de 12:34 Madrid</summary><MorningBrief /></details>
 <nav className='flex flex-wrap gap-2 text-sm'>{['260924','260923','260922','260921','260918','260917'].map(c=><a className='rounded-lg border border-slate-700 px-3 py-2' key={c} href={'?'+c}>{c.slice(4,6)}/{c.slice(2,4)}</a>)}</nav>
 </div></main>;
}