const pulse = [
  ['S&P 500', '7.706,03 · -0,76%'],
  ['Nasdaq', '26.936,04 · -1,13%'],
  ['Dow', '51.511,59 · -0,68%'],
  ['Russell 2000', '2.838,66 · -1,77%'],
  ['VIX', '15,18 · +6,83%'],
  ['US 10Y', '5,11%'],
  ['WTI', 'US$ 92,84 · +2,56%'],
  ['Ouro', 'US$ 4.323,20 · -1,22%'],
  ['Bitcoin', 'US$ 84.392 · -2,09%'],
  ['USD/BRL', '5,16 · +1,23%'],
];

function Edition260923() {
  return (
    <main className='min-h-screen bg-slate-950 text-slate-100'>
      <div className='mx-auto max-w-6xl px-5 py-8 md:px-8 md:py-12'>
        <header className='mb-8 border-b border-slate-800 pb-7'>
          <p className='text-xs font-semibold uppercase tracking-[0.28em] text-cyan-400'>PrimeSphere Intelligence</p>
          <h1 className='mt-3 text-4xl font-semibold md:text-6xl'>AFTER CLOSE</h1>
          <p className='mt-3 text-xl text-slate-300'>Fechamento de Wall Street · 23/09/2026</p>
          <div className='mt-5 inline-block rounded-xl border border-cyan-900/60 bg-cyan-950/20 px-4 py-3 text-sm'><strong className='text-cyan-300'>Atualizado às 22:15 Madrid</strong><p className='mt-1 text-slate-400'>16:15 ET · sessão regular encerrada.</p></div>
          <p className='mt-5 max-w-4xl text-sm leading-7 text-slate-400 md:text-base'>O que mudou durante o pregão: o PMI americano veio bem acima do esperado, os Treasuries dispararam e a curva passou a precificar maior risco de novo aperto do Fed. O resultado foi uma reversão clara do apetite por risco, com queda dos principais índices, pressão maior em small caps e tecnologia e VIX em alta.</p>
          <div className='mt-5 grid gap-3 md:grid-cols-3'><div className='rounded-xl border border-slate-800 bg-slate-900/60 p-4'><p className='font-semibold'>12:31 Madrid · Morning Brief</p><p className='mt-2 text-sm text-slate-400'>Futuros praticamente estáveis; foco em IA, juros e diplomacia.</p></div><div className='rounded-xl border border-slate-800 bg-slate-900/60 p-4'><p className='font-semibold'>15:00 Madrid · Final Pré-Market</p><p className='mt-2 text-sm text-slate-400'>Futuros em leve queda e petróleo recuperando terreno antes do PMI.</p></div><div className='rounded-xl border border-cyan-900/60 bg-cyan-950/20 p-4'><p className='font-semibold text-cyan-300'>22:15 Madrid · After Close</p><p className='mt-2 text-sm text-slate-300'>PMI forte → yields em máxima desde 2007 → índices fecham no vermelho.</p></div></div>
        </header>

        <section className='mb-6 rounded-2xl border border-slate-800 bg-slate-900/60 p-6 md:p-8'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Fechamento em 30 segundos</p><div className='mt-5 grid grid-cols-2 gap-3 md:grid-cols-5'>{pulse.map(([a,b]) => <div key={a} className='rounded-xl border border-slate-800 bg-slate-950/70 p-4'><p className='text-xs text-slate-500'>{a}</p><p className='mt-2 text-lg font-semibold'>{b}</p></div>)}</div><p className='mt-5 text-sm leading-7 text-slate-300'>S&P 500 -0,76%, Nasdaq -1,13% e Dow -0,68% → atividade americana mais forte elevou as apostas de alta de juros → Treasury de 10 anos chegou a 5,11%, enquanto o VIX subiu 6,83%. O Russell 2000 caiu 1,77%, mostrando pressão ainda maior nas empresas menores.</p></section>

        <section className='mb-6 grid gap-4 lg:grid-cols-3'>{[
          ['01','PMI reacende risco de alta do Fed','Manufacturing PMI 57,0 vs 53,5 esperado e Services PMI 58,7 vs 56,0 esperado; Composite avançou a 58,4.','Por que importa: crescimento mais forte reduz a urgência de cortes e elevou a probabilidade percebida de nova alta de juros.'],
          ['02','Treasury 10Y rompe 5%','O rendimento do Treasury de 10 anos terminou perto de 5,11%, cerca de 14 pontos-base acima do fechamento anterior e no maior nível desde 2007.','Por que importa: juros longos mais altos comprimem valuations e atingem principalmente ações de duration longa, tecnologia e small caps.'],
          ['03','Petróleo volta a pressionar','WTI +2,56% a US$ 92,84 e Brent +4,50% a US$ 103,72, apesar das conversas diplomáticas entre EUA e Irã.','Por que importa: energia mais cara reforça o risco inflacionário justamente quando os dados de atividade já estão fortes.'],
        ].map(([n,t,b,i]) => <article key={n} className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><p className='text-3xl font-semibold text-cyan-400'>{n}</p><h2 className='mt-4 text-2xl font-semibold'>{t}</h2><p className='mt-3 text-sm leading-7 text-slate-300'>{b}</p><p className='mt-4 border-t border-slate-800 pt-4 text-sm text-slate-200'>{i}</p></article>)}</section>

        <section className='mb-6 grid gap-6 lg:grid-cols-2'><div className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Setores e temas</p><h2 className='mt-2 text-2xl font-semibold'>Energia lidera; defensivos de juros sofrem</h2><div className='mt-4 space-y-3 text-sm leading-7 text-slate-400'><p><strong className='text-emerald-400'>Energia +0,99%</strong> — único grande setor claramente positivo, acompanhando a alta do petróleo.</p><p><strong className='text-slate-200'>Industriais -0,11%</strong> — melhor resistência entre os setores negativos.</p><p><strong className='text-rose-400'>Utilities -1,92%</strong> e <strong className='text-rose-400'>Real Estate -1,55%</strong> — sensíveis a juros, pressionados pela disparada dos yields.</p><p><strong className='text-rose-400'>Consumer Discretionary -1,50%</strong> — ficou entre os piores grupos do dia.</p><p><strong className='text-rose-400'>Tecnologia -0,47%</strong> — recuou, mas resistiu melhor que o Nasdaq amplo; semicondutores devolveram parte dos ganhos recentes.</p></div></div><div className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Movers do dia</p><h2 className='mt-2 text-2xl font-semibold'>Juros e resultados definem extremos</h2><div className='mt-4 space-y-3 text-sm leading-7 text-slate-400'><p><strong className='text-emerald-400'>META +~1%</strong> — fechou em alta e atingiu máxima de 52 semanas antes de apresentação esperada de Mark Zuckerberg sobre estratégia de IA.</p><p><strong className='text-rose-400'>MCD -~5%</strong> — liderou as quedas do Dow após anunciar plano de investir até US$ 8,5 bilhões até 2036 para modernização de restaurantes e apoio a franqueados.</p><p><strong className='text-rose-400'>PAYX -~9%</strong> — forte queda após resultados, liderando as perdas do S&P 500 e Nasdaq-100.</p><p><strong className='text-rose-400'>SNDK -~3,5% / MU -~2%</strong> — memória devolveu parte da forte alta das sessões anteriores com yields mais altos e realização no tema de chips.</p></div></div></section>

        <section className='mb-6 grid gap-6 lg:grid-cols-2'><div className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Dados econômicos</p><h2 className='mt-2 text-2xl font-semibold'>Atividade surpreende para cima</h2><div className='mt-4 space-y-3 text-sm leading-7 text-slate-400'><p><strong className='text-white'>Manufacturing PMI:</strong> 57,0 actual vs 53,5 consenso vs 53,9 anterior.</p><p><strong className='text-white'>Services PMI:</strong> 58,7 actual vs 56,0 consenso vs 56,5 anterior.</p><p><strong className='text-white'>Composite PMI:</strong> 58,4 vs 56,0 anterior.</p><p>A reação observável foi uma forte alta dos yields e queda das ações. Notícias de mercado atribuíram a mudança à leitura de atividade mais robusta e ao aumento das apostas de alta do Fed.</p></div></div><div className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Earnings After Close</p><h2 className='mt-2 text-2xl font-semibold'>Stitch Fix no radar</h2><p className='mt-4 text-sm leading-7 text-slate-400'>A agenda confirmada aponta a <strong className='text-white'>Stitch Fix (SFIX)</strong> com call de Q4 FY2026 às 23:00 Madrid. Para amanhã, a agenda inclui Darden Restaurants e TD Synnex durante a sessão e Costco após o fechamento. Não adicionamos números de resultados ainda não confirmados.</p></div></section>

        <section className='mb-6 grid gap-6 lg:grid-cols-2'><div className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Brasil → EUA</p><h2 className='mt-2 text-2xl font-semibold'>USD/BRL 5,16 · +1,23%</h2><p className='mt-4 text-sm leading-7 text-slate-400'>O dólar avançou contra o real e também ganhou força globalmente. Para o investidor brasileiro, a alta do USD/BRL amortece em reais parte da queda dos ativos americanos denominados em dólar, embora o efeito final dependa do ativo e do momento da conversão.</p></div><div className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Leitura PrimeSphere</p><h2 className='mt-2 text-2xl font-semibold'>O mercado voltou a negociar juros</h2><p className='mt-4 text-sm leading-7 text-slate-400'>A sessão começou com geopolítica e petróleo no radar, mas terminou dominada pelo choque de juros. O dado forte de atividade mudou o centro da narrativa: menos discussão sobre desaceleração e mais sobre quanto o Fed ainda pode precisar apertar. Isso explica a combinação de yields altos, dólar firme, VIX maior e pressão sobre ações.</p></div></section>

        <section className='mb-6 rounded-2xl border border-cyan-900/50 bg-cyan-950/10 p-6 md:p-8'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Amanhã no radar · 24/09</p><div className='mt-5 grid gap-3 md:grid-cols-5'>{[
          ['1','Jobless Claims','14:30 Madrid · consenso 201 mil vs 196 mil anterior. Mercado vai testar se o trabalho confirma a força mostrada pelos PMIs.'],['2','Fed fala','Williams às 10:10 Madrid; Hammack às 14:50; Paulson às 15:00. Comunicação ganha peso com yields acima de 5%.'],['3','EUA–China','Encontro Trump–Xi mantém tecnologia, comércio e IA expostos a headlines.'],['4','US 10Y 5,11%','Nível-chave para valuations: nova alta tende a manter pressão sobre growth e small caps.'],['5','Costco','COST reporta Q4 FY2026 após o fechamento; consumo e margens entram no radar.'],
        ].map(([n,t,b]) => <div key={n} className='rounded-xl border border-slate-800 bg-slate-950/60 p-4'><p className='text-cyan-400'>{n}</p><p className='mt-2 font-semibold'>{t}</p><p className='mt-3 text-xs leading-5 text-slate-400'>{b}</p></div>)}</div></section>

        <section className='mb-6 rounded-2xl border border-slate-800 bg-slate-900/60 p-6 md:p-8'><p className='text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400'>Conclusão</p><h2 className='mt-2 text-2xl font-semibold'>O que aconteceu hoje?</h2><p className='mt-4 text-sm leading-7 text-slate-300'>PMIs fortes → Treasury de 10 anos a 5,11% → ações recuam e VIX sobe. O petróleo também avançou, reforçando a combinação desconfortável de atividade forte, inflação potencial e juros elevados.</p><h2 className='mt-6 text-2xl font-semibold'>O que já importa para amanhã?</h2><p className='mt-4 text-sm leading-7 text-slate-300'>A sustentação do 10Y acima de 5%, os pedidos de seguro-desemprego, a sequência de discursos do Fed e as headlines EUA–China serão os principais testes para saber se a correção de hoje ganha continuidade ou encontra estabilização.</p></section>

        <section className='rounded-2xl border border-slate-800 bg-slate-900/60 p-6 md:p-8'><h2 className='text-xl font-semibold'>Fontes e validação</h2><div className='mt-4 space-y-2 text-sm leading-6 text-slate-400'><p>Bigdata.com / FMP, snapshot de mercado de 23/09/2026: índices, setores, Treasury yields, petróleo, ouro, Bitcoin e USD/BRL.</p><p>Bigdata.com / calendário econômico: S&P Global Manufacturing, Services e Composite PMI.</p><p>Bigdata.com / notícias de fechamento: reação dos Treasuries, probabilidades de política monetária e movers confirmados.</p><p>Bigdata.com / calendário corporativo: earnings e calls de 23–24/09/2026.</p><p className='pt-2 text-xs text-slate-500'>Conteúdo informativo e educacional; não constitui recomendação individual de investimento.</p></div></section>

        <section className='mt-6 rounded-2xl border border-slate-800 bg-slate-900/60 p-6'><h2 className='text-xl font-semibold'>Arquivo de análises</h2><div className='mt-4 flex flex-wrap gap-3'>{['260923','260922','260921','260918','260917'].map(code => <a key={code} href={'?' + code} className='rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:border-slate-500'>?{code}</a>)}</div></section>
        <footer className='mt-10 border-t border-slate-800 pt-5 text-xs leading-5 text-slate-500'>PrimeSphere Intelligence · Wall Street explicado em português para o investidor brasileiro.</footer>
      </div>
    </main>
  );
}

export default Edition260923;
